apiVersion: zalando.org/v1
kind: TestFabricGateway
metadata:
  name: test-gateway-operator-stack-managed
spec:
  x-external-service-provider:
    stackSetName: gw-test-stack
    hosts:
      - ss-test-gateway-operator.{{ CLUSTER }}.zalan.do
  x-fabric-admins:
  - bmooney
  - fmoloney
  - cgallagher
  - changedForTesting
  paths:
    /resources:
      get: {}