apiVersion: v1
kind: Service
metadata:
  name: gateway-test-app
  labels:
    application: gateway-test-app
spec:
  selector:
    application: gateway-test-app
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  type: ClusterIP