apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-test-app
  labels:
    application: gateway-test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      application: gateway-test-app
  template:
    metadata:
      labels:
        application: gateway-test-app
    spec:
      containers:
        - name: gateway-test-app
          image: jmalloc/echo-server:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 1
              memory: 512Mi
            limits:
              memory: 512Mi