apiVersion: zalando.org/v1
kind: FabricGateway
metadata:
  name: fgtestapp-operator-whitelisting
spec:
  x-fabric-service:
  - host: wl-fgtestapp-operator.{{ CLUSTER }}.zalan.do
    serviceName: gateway-test-app
  x-fabric-whitelist:
  - stups_fabric-event-scheduler
  - stups_changedForTesting
  paths:
    /resources:
      get:
        x-fabric-privileges:
        - fabric-demo-app.read
        x-fabric-ratelimits:
          default-rate: 10000
          target:
            stups_fabric-demo-app: 200
      post:
        x-fabric-privileges:
        - fabric-demo-app.write
    /resources/{id}:
      get:
        x-fabric-whitelist:
          service-list:
            - stups_metacontroller
    /other-resource:
      get:
        x-fabric-whitelist:
          state: disabled
          service-list: []
      post:
        x-fabric-whitelist:
          service-list: []
    /resources/{id}/sub-resources/{id}:
      get:
        x-fabric-whitelist:
          service-list:
            - stups_metacontroller