apiVersion: zalando.org/v1
kind: FabricGateway
metadata:
  name: gateway-operator-bug2098
spec:
  x-fabric-service:
  - host: bug2098-gateway-operator.{{ CLUSTER }}.zalan.do
    serviceName: gateway-test-app
    servicePort: http
  x-fabric-admins:
  - bmooney
  - fmoloney
  - cgallagher
  - changedForTesting
  paths:
    /{id}:
      get:
        x-fabric-privileges:
          - fabric-demo-app.nonexistant
    /**:
      get: {}
    /resources/{id}:
      get:
        x-fabric-privileges:
          - fabric-demo-app.nonexistant