apiVersion: zalando.org/v1
kind: TestFabricGateway
metadata:
  name: brian-test-ss-integration
spec:
  x-external-service-provider:
    stackSetName: ss-int-stack
    hosts:
      - brian-ss-int-test.playground.zalan.do
  x-fabric-admins:
    - bmooney
    - fmoloney
  paths:
    /resources:
      get: {}