apiVersion: zalando.org/v1
kind: TestFabricGateway
metadata:
  name: invalid-resource
spec:
  x-fabric-service:
  - host: test.playground.zalan.do
    serviceName: fgtestapp
  x-external-service-provider:
    stackSetName: ss-stack
    hosts:
      - test.playground.zalan.do
  paths:
    /api:
      get: {}