apiVersion: zalando.org/v1
kind: TestFabricGateway
metadata:
  name: managed-by-stackset-1
spec:
  x-external-service-provider:
    stackSetName: ss-stack
    hosts:
      - test.playground.zalan.do
  paths:
    /api:
      get: {}