apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: fgtestapp-operator
webhooks:
  - name: fabricgateway.check.webhook
    failurePolicy: Fail
    sideEffects: None
    rules:
      - apiGroups:
          - zalando.org
        apiVersions:
          - "*"
        operations:
          - CREATE
          - UPDATE
        resources:
          - fabricgateways
    clientConfig:
      service:
        namespace: fabric
        name: fgtestapp-operator
        path: "/validate"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUV1VENDQXFHZ0F3SUJBZ0lFSWdtS1ZqQU5CZ2txaGtpRzl3MEJBUXdGQURCck1Rc3dDUVlEVlFRR0V3SkoNClJURVBNQTBHQTFVRUNCTUdSSFZpYkdsdU1ROHdEUVlEVlFRSEV3WkVkV0pzYVc0eEVEQU9CZ05WQkFvVEIxcGgNCmJHRnVaRzh4RnpBVkJnTlZCQXNURGtsdVpuSmhjM1J5ZFdOMGRYSmxNUTh3RFFZRFZRUURFd1pHWVdKeWFXTXcNCkhoY05NVGt3T0RJNE1UQTBPVE0zV2hjTk5EY3dNVEV5TVRBME9UTTNXakJwTVFzd0NRWURWUVFHRXdKSlJURVANCk1BMEdBMVVFQ0JNR1JIVmliR2x1TVE4d0RRWURWUVFIRXdaRWRXSnNhVzR4RURBT0JnTlZCQW9UQjFwaGJHRnUNClpHOHhEekFOQmdOVkJBc1RCa1poWW5KcFl6RVZNQk1HQTFVRUF3d01LaTVtWVdKeWFXTXVjM1pqTUlJQklqQU4NCkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXA3M2tLMTNnRE1iRFdpZTJQWUdXOUJ4N2lYK0oNCk9KK2ppNGJlQjdKclpOZi9WQWRjQThFQzRwK0RZODkzNEJwUVZOaisyS1NqeEplSHBYWmI1SXl0UldmWlJQQSsNCnE5a1AwbTRXaDFtZjVyRTZORjMyQWF3SGZUY2VINzF2L1BJQnFzWFQxTkUwcHB0T3ZWeFA2VlRCemtDbExqMGINCk5WSVR0YTRhZDVGb1p3YTRJVlVLTEpiTkRCUThyK2ZDWVFzUlZrWkRwRGtZRWk5eVg4Yk9pWndmclByMWNuWUoNCkRCRXRrNXJxYXNOalJQRW1saElXK05wY2RLdCtaOWpRaVJ2d21JcVBNNCtpbmgyRmhYVmp3U1JzK1hvbktNVVcNCm1RU0VkZS9YK21DcEo2bVdnNUphaWhyMTdIT1NDNHdZMXdDZkZGVzBKTVkvR2ZvcUZHK29JWjRCMVFJREFRQUINCm8yY3daVEFkQmdOVkhRNEVGZ1FVeVdPKzlwb2s2WW5xZlpKUDFFeGNMN2RFS09Vd0RnWURWUjBQQVFIL0JBUUQNCkFnV2dNQjhHQTFVZEl3UVlNQmFBRkh0c2ZLc2EyTk9JUy81VFM1NEMxbVBSanNNcU1CTUdBMVVkSlFRTU1Bb0cNCkNDc0dBUVVGQndNQk1BMEdDU3FHU0liM0RRRUJEQVVBQTRJQ0FRQzVmTEdscXlGTXVsbzRjcThsOHhma25EVHANCldhY09LKzNoZXRuVmJoSGxOOHpoZnBHVDV5blFydGphOHpCY0NKaXFxUUlWcHdrMzJCRThRQzBia3Rlb0hMYzANCjA1MFF2OWh6OFNjTDA1VzR3eXY3WXRHa3VIcjFERGxST2p0bmhGQWRKS0MvTTM4UXUyZDFwS0h3aXlnZlBsN1ANCnVRbXlxejZQYmdMWFFkb3oycG5nMnl3ODdaV0k1d3FET05ja0dxUEtIQWJLZzk5K2hsZjF0ZlQvSXU1MTVOT2sNCnV3NDArV1dkSW01Ni9EekVWZTgvZXJVeE0xb2gyR3VqRUN6eEQ3TzVoNEtPQytBT3ZqT2Q4RVhTODJZS2ttci8NCjZvc0FnVnpTanZnVDBNdGVQYUpNb2tSM2JXNmhtRi9JYU53RUpuUmpZbmxBYlI5TFZTb2czV3hyTkhkWVZCZGkNClY3WTdGc3F0RWs5UDVmeFpMaTg0dUpvYmxKSEo0Q2g4SjdJZTA3aFplTWdGV0xtRzBRL3lIeUM5ZUZlM3BFc3QNClFFU0Iva0YvL09PS0pndW5mS2p1UzVOVk5TanlyZTdlQ0s3dzNFbmw0bVJQM0hiMExvU0NFaEF6MDFBVGRFSWMNCis4VE5aZnZ4aVF6QXFPNExlekErcS9LUUc3Qmtnb2dVVVkzeWxWMmdIWU9Lbk1Bb1NnVldhR2NjcTNON2dENkgNCmlDVzdBUHVyaEpXU1ZzYzBiR1hPOGpGelVpZVpjSXhUeDdscUVQREYxbDhSc2ptWnM4Z2l5S0JJUk9VLzNmeTINClpKNjJtMGIydGk2elVUTm5ibWVzU1NDdU9WUk1Ya01WTjBibHJpVjl6UmE2VGxWK1M3NEk2VjFQZVpHSzBxT3QNClMyUzVBVjJCM2M1Y2haMlJwZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
