apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "{{{ COMPOSITE_CONTROLLER_NAME }}}-metacontroller"
rules:
  - apiGroups:
      - zalando.org
    resources:
      - "{{{ CRD_PLURAL }}}"
      - "{{{ CRD_PLURAL }}}/status"
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - extensions
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "{{{ COMPOSITE_CONTROLLER_NAME }}}-metacontroller"
subjects:
  - kind: ServiceAccount
    name: fabric
    namespace: fabric
roleRef:
  kind: ClusterRole
  name: "{{{ COMPOSITE_CONTROLLER_NAME }}}-metacontroller"
  apiGroup: rbac.authorization.k8s.io
