apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "{{{ COMPOSITE_CONTROLLER_NAME }}}"
rules:
  - apiGroups:
      - zalando.org
    resources:
      - stacksets
    verbs:
      - get