apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-operator
  annotations:
    downscaler/exclude: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      application: gateway-operator
  template:
    metadata:
      labels:
        application: gateway-operator
    spec:
      containers:
        - name: gateway-operator
          image: "{{{IMAGE}}}:{{{VERSION}}}"
          env:
          - name: LOG_LEVEL
            value: DEBUG
          - name: WEBHOOK_TLS_ENABLED
            value: "TRUE"
          - name: WEBHOOK_TLS_UNSAFE_KEYSTORE_ENABLED
            value: "TRUE"
          - name: VERSIONED_HOSTS_ENABLED
            value: "TRUE"
          - name: VERSIONED_HOSTS_BASE_DOMAIN
            value: "{{{CLUSTER}}}.zalan.do"
          ports:
            - containerPort: 8080
            - containerPort: 8443
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
          resources:
            requests:
              cpu: 1
              memory: 1024Mi
            limits:
              memory: 1024Mi