apiVersion: "zalando.org/v1"
kind: PlatformCredentialsSet
metadata:
  name: testOperatorName-credentials
spec:
  application: fabric-demo-app
  token_version: v2
  tokens:
    test-app:
      privileges:
      - com.zalando::fabric-demo-app.read
      - com.zalando::fabric-demo-app.write