apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: "fabricgateways.zalando.org"
spec:
  group: zalando.org
  version: v1
  names:
    kind: "FabricGateway"
    singular: "fabricgateway"
    plural: "fabricgateways"
    shortNames:
      - "fg"
  scope: Namespaced
  additionalPrinterColumns:
    - name: Ingress_Count
      type: integer
      description: The number of ingressii owned by this gateway
      JSONPath: .status.num_owned_ingress
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      required:
        - spec
      properties:
        spec:
          required:
            - paths
          properties:
            x-fabric-service:
              type: array
              items:
                type: object
                required:
                  - host
                  - serviceName
                properties:
                  host:
                    type: string
                    description: This is the pulic host name for the service
                    example: app-id.cluster-name.zalan.do
                  serviceName:
                    type: string
                    description: This is the name of the K8s service which Skipper should target when forwarding requests
                    example: app-id-service
                  servicePort:
                    type: string
                    description: The port to use for the service. Must be the name of a named port defined in your k8s service. Defaults to "http". See https://kubernetes.io/docs/concepts/services-networking/service/#multi-port-services
                    example: http
                    pattern: '^[a-z][-a-z0-9]*[^-]$'
            x-external-service-provider:
              type: object
              required:
                - stackSetName
                - hosts
              properties:
                stackSetName:
                  type: string
                hosts:
                  type: array
                  minItems: 1
                  items:
                    type: string
            x-fabric-admins:
              type: array
              minItems: 0
              items:
                type: string
                description: |-
                  UID of a user which will have open access to the full API. This will exclude this uid from
                  any rate limits or authorization
                example: jbloggs
            x-fabric-whitelist:
              type: array
              items:
                type: string
                description: |-
                  UID of a service which will be allowed access to the API if it matches all other authorization
                  requirements. If there is a whitelist present, then ONLY services which are referenced in the whitelist
                  will be able to access the API even if they match all other authorization requirements. If the whitelist
                  is empty, then no service tokens can access via the gateway
                example: stups_some-service-name
            x-fabric-cors-support:
              type: object
              description: |
                This section configures Cross-Origin Resource Sharing (CORS) support in the gateway.
                When this is configured:
                  1. An HTTP OPTIONS endpoint will be created for each path, fulfilling the preflight requirement for CORS.
                  2. Each route defined in this gateway will return the `access-control-allow-origin` header for origins configured here.
              required:
                - allowedOrigins
                - allowedHeaders
              properties:
                allowedOrigins:
                  type: array
                  minItems: 1
                  description: |
                    List of origins that should be allowed to access your API. Defaults to an empty list.
                  items:
                    type: string
                    description: |
                      A hostname that should be allowed access your API. "*" is not allowed.
                    example: foo.example.com
                allowedHeaders:
                  type: array
                  minItems: 1
                  description: |
                    List of headers which are allowed to be used as part of CORS requests. Typically you should list Authorization, Content-Type, and X-Flow-Id at a minimum.
                  items:
                    type: string
                    description: |
                      A header which an XHR request should be allowed to use.
                    example: Authorization
            x-fabric-employee-access:
              type: object
              description: |
                The `user-list` should only be populated if `type` is set to `allow_list`. If `type` is not
                present, it will be defaulted to `scoped_access`
              properties:
                user-list:
                  type: array
                  items:
                    type: string
                    description: |-
                      UID of a user who should bypass scope checks, since user tokens can't have scopes.
                type:
                  type: string
                  enum:
                    - allow_list
                    - allow_all
                    - deny_all
                  description: |-
                    If `allow_list` is selected, then the `user-list` property must be populated, otherwise it
                    is ignored. If allow_all is selected, any token which is Employee realm will be able to
                    access the endpoint in spite of any scope restrictions. If `deny_all` is selected, then any
                    employee realm token will be rejected even if there are no scope restrictions beyond `uid`.
                    If no employee access configuration is configured then employee access will work as per normal scope
                    rules; i.e. employees will have access to routes which aren't scope protected. This can be overridden
                    on a per route basis.
            x-fabric-compression-support:
              type: object
              description: |
                Enable compression on response payloads. The actual compression work will be delegated to a Skipper filter
                (See https://opensource.zalando.com/skipper/reference/filters/#compress). If this object is not present,
                then no compression of the response payload will happen in Skipper. If present the response payload will
                be conditionally compressed based off of the requirements outlined in the Skipper filter `compress`
                documentation.
              required:
                - compressionFactor
                - encoding
              properties:
                compressionFactor:
                  type: integer
                  description: |
                    Set the compression level where 0 means no-compression, 1 means best-speed and 9 means
                    best-compression
                  minimum: 0
                  maximum: 9
                encoding:
                  type: string
                  description: |
                    Specify the encoding to compress. This must match the Content-Type of the response payload for
                    compression to happen
            paths:
              type: object
              minProperties: 1
              description: |-
                Each key represents a path in the API. A single star matches a value between two slashes in a HTTP path
              example: /api/resource, /api/resource/*
              additionalProperties:
                type: object
                minProperties: 1
                description: Each key represents a supported HTTP verb on the parent path
                example: get, head, put, post, patch, delete
                additionalProperties:
                  type: object
                  properties:
                    x-fabric-privileges:
                      type: array
                      minItems: 1
                      items:
                        type: string
                        description: The name of a scope which will be extracted from the bearer token
                        example: uid, service-name.write
                    x-fabric-ratelimits:
                      type: object
                      required:
                        - default-rate
                      properties:
                        default-rate:
                          type: integer
                          minimum: 1
                          description: |-
                            Non user specific value to apply to the route. If a client makes more requests than this
                            value within the defined period, then they will start getting HTTP 429 responses.
                        period:
                          type: string
                          enum:
                            - second
                            - minute
                            - hour
                        target:
                          type: object
                          description: |-
                            A uid specific number of requests that can be made within the period before rate
                            limiting is applied
                          additionalProperties:
                            type: integer
                    x-fabric-whitelist:
                      type: object
                      required:
                        - service-list
                      properties:
                        state:
                          type: string
                          enum:
                            - enabled
                            - disabled
                          description: Turns whitelisting on and off for this path/operation. Default is `enabled`
                        service-list:
                          type: array
                          items:
                            type: string
                            description: |-
                              UID of a service which will be allowed access to the API if it matches all other authorization
                              requirements. If there is a whitelist present, then ONLY services which are referenced in the whitelist
                              will be able to access the API even if they match all other authorization requirements
                            example: stups_some-service-name
                    x-fabric-employee-access:
                      type: object
                      description: |
                        The `user-list` should only be populated if `type` is set to `allow_list`. If `type` is not
                        present, it will be defaulted to `scoped_access`
                      properties:
                        user-list:
                          type: array
                          items:
                            type: string
                            description: |-
                              UID of a user who should bypass scope checks, since user tokens can't have scopes.
                        type:
                          type: string
                          enum:
                            - allow_list
                            - allow_all
                            - deny_all
                          description: |-
                            If `allow_list` is selected, then the `user-list` property must be populated, otherwise it
                            is ignored. If allow_all is selected, any token which is Employee realm will be able to
                            access the endpoint in spite of any scope restrictions. If `deny_all` is selected, then any
                            employee realm token will be rejected even if there are no scope restrictions beyond `uid`.
                            If the employee access route config object is not present, the employee access configuration
                            is inherited from any globally defined employee access config.
                    x-fabric-static-response:
                      type: object
                      description: |
                        This property is used to configure a static, hard-coded response for a route. The request does not reach the backend,
                        the response is returned immediately from skipper.
                      properties:
                        status:
                          type: integer
                          description: The status code to use in the static response.
                        headers:
                          type: object
                          description: |-
                            The headers which should be present in the static response. This is an object whose values are all Strings.
                          additionalProperties:
                            type: string
                        body:
                          type: string
                          description: The body of the static response.
---

apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: "gateway-operator"
webhooks:
  - name: "gateway-operator.check.webhook"
    failurePolicy: Fail
    sideEffects: None
    rules:
      - apiGroups:
          - zalando.org
        apiVersions:
          - "*"
        operations:
          - CREATE
          - UPDATE
        resources:
          - "fabricgateways"
    clientConfig:
      service:
        namespace: fabric
        name: "gateway-operator"
        path: "/validate"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUUvRENDQXVTZ0F3SUJBZ0lFSUVJenFUQU5CZ2txaGtpRzl3MEJBUXdGQURCck1Rc3dDUVlEVlFRR0V3SkoNClJURVBNQTBHQTFVRUNCTUdSSFZpYkdsdU1ROHdEUVlEVlFRSEV3WkVkV0pzYVc0eEVEQU9CZ05WQkFvVEIxcGgNCmJHRnVaRzh4RnpBVkJnTlZCQXNURGtsdVpuSmhjM1J5ZFdOMGRYSmxNUTh3RFFZRFZRUURFd1pHWVdKeWFXTXcNCkhoY05NakV3TWpFM01UWTFPVEEzV2hjTk5EZ3dOekEwTVRZMU9UQTNXakI5TVFzd0NRWURWUVFHRXdKSlJURVANCk1BMEdBMVVFQ0JNR1JIVmliR2x1TVE4d0RRWURWUVFIRXdaRWRXSnNhVzR4RURBT0JnTlZCQW9UQjFwaGJHRnUNClpHOHhEekFOQmdOVkJBc1RCa1poWW5KcFl6RXBNQ2NHQTFVRUF4TWdkR1Z6ZEMxbllYUmxkMkY1TFc5d1pYSmgNCmRHOXlMbVpoWW5KcFl5NXpkbU13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQ3kNCkcvUldKSzhhSDY2ZjFWZVlPK3FHdnpIbDhKOTdxK3lzc3pqcWQ5ZGR3dDFsV1k4dVhsTEs5WkF2NnNBUVlJcXMNCnRTUENDQWV6eG1PZFUyYXR6bmNGTmtSZTJoNmJtN3J2VkVOY0NVRXltUEdWTXJrL0J4MEdzSi9MNFhMMEZJQUINCko0Smdqcjh1RUhZMkpYZjhzMVdSOFM4UmRFWTF0KzZPdmVmNG8zeG9hVWFXVElRaGV3MFYxUkVhUDJpN3ZXbm8NCjE2TFc0ZXFncURSYVBSVk1vSVhydjExT2x3UG1jeWdjS1ZkcHl2RjB6Z0VJNTRjZVVGS2ttVnphemVaZ0ZxQUgNCldxUkVCVVc2WHRXTUVMTnhVS0QycDBoQ0NybmNIVkNsbkYvemF4Qmg0OExVVzFtMWRKdDRESFpZMk4zNHYrR1UNCnhmUHMvd2tGd2N3RU1kMkZBWU1sQWdNQkFBR2pnWlV3Z1pJd0hRWURWUjBPQkJZRUZENzRUTkc1UmdVZnNzTUoNCjJnYmRNYWh5VTZrSk1BNEdBMVVkRHdFQi93UUVBd0lGb0RBckJnTlZIUkVFSkRBaWdpQjBaWE4wTFdkaGRHVjMNCllYa3RiM0JsY21GMGIzSXVabUZpY21sakxuTjJZekFmQmdOVkhTTUVHREFXZ0JSSHNYSzRYTjZkYW96MHhDZmMNCjlQei9XK1VsSGpBVEJnTlZIU1VFRERBS0JnZ3JCZ0VGQlFjREFUQU5CZ2txaGtpRzl3MEJBUXdGQUFPQ0FnRUENCmQrLzRPUGZXNm12K3l6Y1VxT1hKZExIWnF1RXlYZEovWXZ3SGU4RlRabFBhekpkVXJBQUtFdmR1WVBOMmJpQ2INCmREK0p2Sk0rZnMrY28vSzdaYk8rYUthZUZ0UzYraUI3TUhtZm5Ed1p2QlR3WlJVQ0lIZG0ydnhBMG4yWlhFSXkNCnpXbVFocGJBcit2cTViOVpNalBuTUJYc3Viek43aGh0dS9Kc3A4VGtRSkNuSVh6alllZHhsMjlWalRNYzJmRFINCnBjalQ4eU5XSXFRZGZFVGhjbSs4aFA4bUxLRXhaakNiNFRnQ3lJRWtlQ1NQbHYwdHZVckt0SnAwRmp6bHhTUm8NCmpMdFh1cTBSLzNGV1pGaDN6UGdtWWFnYlFyaGpCMmdwdTB4SmQrdzRlMkNSWlIyWFd6K25qRHFzKytqaGc0Uk0NCmZOYklYSnordlBvclZGdzN4QnQrRmdHekdzTVd1YUIxR083OU15SWZPZUVydmRQVGh2ejI0MkNpY21RVnVqdWsNCkJLUXEwSzhnQ1kwWGVOVVp1bm8vdlBEZ3BkYTV5ZWlLNzBMWkF6M051c3NnRVRXamxqczFPL2hLRmdaZjlVUjINClUrbkJYR1psc0d6Tkgwb0RlRlNMODRSZWExbE5TSXAybzNkTjlLNkZCQnB5YUFNQ2lVYzVESUd3NDJ0Njg4ZnkNCmg5dm1GTXJ2UmZrUG5IbThkWW0rK2NXTEJKeXJxekJyNVo0NTRoM0lYbFJIZGNWdFJBc09xTnUva1B1VEZNRloNCjVLUWUwbjFxSFdQQWxrSDk5M1BzRTVXM0licDNXbU9jQUFVdWh6ZXBjQmloYWRVQ3NkOFJlNHIrRmNTa1h2REoNCnJIa2FiRmxPY1hodjBGY0RHV3J3NDhwK3JPTFVyNnltOTYxWENaWnA3WWs9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K

---

apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: "gateway-operator"
spec:
  generateSelector: true
  resyncPeriodSeconds: 5
  parentResource:
    apiVersion: zalando.org/v1
    resource: "fabricgateways"
  childResources:
    - apiVersion: extensions/v1beta1
      resource: ingresses
      updateStrategy:
        method: InPlace
  hooks:
    sync:
      webhook:
        url: "http://gateway-operator/synch"
---

apiVersion: v1
kind: Service
metadata:
  name: "gateway-operator"
spec:
  selector:
    application: "gateway-operator"
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8443
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: "gateway-operator"
  annotations:
    downscaler/exclude: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      application: "gateway-operator"
  template:
    metadata:
      labels:
        application: "gateway-operator"
    spec:
      containers:
        - name: "gateway-operator"
          image: "registry.opensource.zalan.do/fabric/gateway-k8s-operator:master-4"
          env:
          - name: LOG_LEVEL
            value: INFO
          - name: WEBHOOK_TLS_ENABLED
            value: "TRUE"
          - name: WEBHOOK_TLS_UNSAFE_KEYSTORE_ENABLED
            value: "TRUE"
          - name: VERSIONED_HOSTS_ENABLED
            value: "TRUE"
          - name: VERSIONED_HOSTS_BASE_DOMAIN
            value: "example.com"
          - name: ANNOTATION_ALLOWLIST
            value: "{{{ ANNOTATION_ALLOWLIST }}}"
          - name: ADDITIONAL_FILTER_ALLOWLIST
            value: "{{{ ADDITIONAL_FILTER_ALLOWLIST }}}"
          ports:
            - containerPort: 8080
            - containerPort: 8443
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
          resources:
            requests:
              cpu: 1
              memory: 1024Mi
            limits:
              memory: 1024Mi